apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost    
  namespace: argocd   
  labels:
    type: kubecost   
spec:
  project: default    # argcd project
  sources:
    - repoURL: 'git@github.com:s10vincen/Helm-charts-demo.git'   
      targetRevision: main                                       
      ref: values                                                 # A reference name so this repo can be called later (e.g., $values/...).

    - repoURL: 'https://kubecost.github.io/cost-analyzer/'                     
      chart: cost-analyzer                              # The name of the Helm chart to deploy.
      targetRevision: "2.8.13"                                    # The version of the Helm chart to deploy.
      helm:
        releaseName: kubecost     #The Helm release name
        valueFiles:     #Extra override values files.
          - $values/kubecost/dev-values.yaml   # Pulls the file from the other repo defined above line 12
  destination:
    namespace: kubecost      # ArgoCD will deploy resources in this namespace
    name: 'in-cluster'      
  syncPolicy:              
    automated:           
      prune: true       
    syncOptions:
      - CreateNamespace=true #
      - ServerSideApply=true  