name: CI/CD vinno

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: [self-hosted, linux]  # Uses self-hosted runner with 'linux' label
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: npm test